- name: Install MySQL server
  apt: "pkg={{item}} state=latest force=yes "
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb
    - libmysqlclient-dev
  tags:
    - mysql

- name: Create user in MySQL
  mysql_user: name={{ db_username }} password={{ db_password }} priv=*.*:ALL state=present

- name: Create database
  mysql_db: >
    name={{ app_name }}_production
    state=present
    encoding='UTF8'
  tags:
    - mysql
