- name: Install logwatch
  apt: "pkg={{item}} state=latest force=yes "
  with_items:
    - logwatch
  tags: logwatch

- name: Configure logwatch file
  template: >
    src=logwatch.conf.j2
    dest=/usr/share/logwatch/default.conf/logwatch.conf
  tags: logwatch